# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Trivios Tournaments' do
  pod 'libPusher', '~> 1.6'
  pod 'Primus', '~> 0.0.7'
  pod 'JSQMessagesViewController' 
  pod "CSStickyHeaderFlowLayout"

end

target 'Trivios TournamentsTests' do

end

