# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TriviaSwag' do
  pod 'libPusher', '~> 1.6'
  pod 'Primus', '~> 0.0.7'
  pod 'JSQMessagesViewController' 
  pod "CSStickyHeaderFlowLayout"
end

target 'TriviaSwagTests' do

end

target 'TriviaSwagUITests' do

end

