# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'TestStoryBoard' do

    pod 'Primus'
    pod 'SocketRocket'
    pod 'libPusher', '~> 1.6.1'
    end

target 'TestStoryBoard' do

end

target 'TestStoryBoard' do

end
