# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'GStack-Swift-SDK' do
    pod 'Primus', '~> 0.0.7'
    pod ’SocketRocket’
	pod ‘libPusher’,’~> 1.6.1’
end

target 'GStack-Swift-SDKTests' do

end

target 'GStack-Swift-SDKUITests' do

end

